version: '3.9'

services:

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGO_CONNECT=mongodb://mongo:27017/test
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - pgdata:/var/lib/mongo/data

volumes:
  pgdata: {}