name: ci

on: 
  push:
    branches:
      - "main"
jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v4
          -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - # there is now way to compose services right now, only image by image with bake, returning here later
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              push: true
              target: prod
              tags: ${{ secrets.DOCKER_USERNAME }}
