name: ci

on: 
  push:
    branches:
      - "main"
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose
        uses: docker/compose@v2
      - name: Login to Docker Hub (if needed)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and run services
        run: docker compose up -d
